name: ItemInverter
version: 1.0
author: Windsority
main: windsority.iteminverter.InverterMain
commands:
    inverter:
        description: Change your item's 
        permission: ItemInverter.use
        usage: |
            /inverter
            --------------------------------------------
            §r/inverter add [id] [formula] 
            §r/inverter remove [formula] 
            §r/inverter list
            §r/inverter detail [formula] 
            §r/inverter enable [player] [formula] 
            §r/inverter disable [player] [formula] 
            §r--------------------------------------------
permissions:
    ItemInverter.use:
        default: op
